version: '3.9'

services:
  mysql_db:
    image: mysql:8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Talonyhtio_App 
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql 

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
    depends_on:
      - mysql_db

volumes:
  mysql_data: